version: '3.9'

services:

  mysql:
    image: mysql:5.7
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.1"
          memory: 20M
      restart_policy:
        condition: on-failure
    ports: 
      - "3306:3306"
    ulimits:
      nofile: 
        soft: 1048576
        hard: 1048576
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    networks:
      - rede_teste

  wordpress:
    image: wordpress:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.1"
          memory: 20M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wordpress
    networks:
      - rede_teste

  redis:
    image: redis:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.1"
          memory: 20M
      restart_policy:
        condition: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - rede_teste

  mysql-exporter:
    image: prom/mysqld-exporter
    deploy:
      replicas: 1
    command: 
     - --config.my-cnf=/cfg/.my.cnf
     - --mysqld.address=mysql:3306
    ports:
      - 9104:9104
    volumes:
      - "./.my.cnf:/cfg/.my.cnf"
    networks:
      - rede_teste
    depends_on:
      - mysql

  prometheus:
    image: prom/prometheus
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1G
        reservations:
          cpus: "0.1"
          memory: 20M
      restart_policy:
        condition: on-failure
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - rede_teste

  grafana:
    image: grafana/grafana:latest
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 64M
        reservations:
          cpus: '0.50'
          memory: 32M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - rede_teste

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    deploy:
      mode: global
    ports:
      - "8081:8081"
    networks:
      - rede_teste

networks:
 rede_teste:

volumes:
  mysql_data:
  redis_data:
  wordpress_data:
  prometheus_data:
  grafana_data: